# module for expected headers in csvs
module NursesCSV
  HEADERS = [
    'Id', 'Email', 'Reset password sent at', 'Remember created at',
    'Sign in count', 'Current sign in at', 'Last sign in at',
    'Current sign in ip', 'Last sign in ip', 'Created at', 'Updated at',
    'Role', 'Phone', 'First name', 'Last name', 'Locale', 'Timezone', 'Type',
    'Family health unit name', 'Confirmation token', 'Confirmed at',
    'Confirmation sent at', 'Unconfirmed email', 'Id [Nurse supervisor]',
    'Email [Nurse supervisor]', 'Reset password sent at [Nurse supervisor]',
    'Remember created at [Nurse supervisor]',
    'Sign in count [Nurse supervisor]',
    'Current sign in at [Nurse supervisor]',
    'Last sign in at [Nurse supervisor]',
    'Current sign in ip [Nurse supervisor]',
    'Last sign in ip [Nurse supervisor]', 'Created at [Nurse supervisor]',
    'Updated at [Nurse supervisor]', 'Role [Nurse supervisor]',
    'Phone [Nurse supervisor]', 'First name [Nurse supervisor]',
    'Last name [Nurse supervisor]', 'Locale [Nurse supervisor]',
    'Timezone [Nurse supervisor]', 'Type [Nurse supervisor]',
    'Nurse supervisor [Nurse supervisor]',
    'Family health unit name [Nurse supervisor]',
    'Confirmation token [Nurse supervisor]',
    'Confirmed at [Nurse supervisor]',
    'Confirmation sent at [Nurse supervisor]',
    'Unconfirmed email [Nurse supervisor]', 'Id [Participants]',
    'First name [Participants]', 'Last name [Participants]',
    'Participant ID [Participants]', 'Family health unit [Participants]',
    'Telephone [Participants]', 'Home address [Participants]',
    'Birth date [Participants]', 'Gender [Participants]',
    'Status [Participants]', 'Emergency contact (name) [Participants]',
    'Telephone [Participants]', 'Date added to dashboard [Participants]',
    'Updated at [Participants]', 'Locale [Participants]',
    'Alternate phone 1 [Participants]', 'Alternate phone 2 [Participants]',
    'Contact person [Participants]', 'Relationship [Participants]',
    'Relationship [Participants]', 'Contact person [Participants]',
    'Relationship [Participants]', 'Relationship [Participants]',
    'Relationship [Participants]', 'Relationship [Participants]',
    'Address [Participants]', 'Cell phone [Participants]',
    'Cell phone [Participants]', 'Id [Nurse tasks]', 'Type [Nurse tasks]',
    'Status [Nurse tasks]', 'Scheduled at [Nurse tasks]',
    'Overdue at [Nurse tasks]', 'Created at [Nurse tasks]',
    'Updated at [Nurse tasks]'
  ].freeze
end
