# module for expected headers in csvs
module ParticipantsCSV
  HEADERS = [
    'Id', 'First name', 'Last name', 'Participant ID', 'Family health unit',
    'Telephone', 'Home address', 'Birth date', 'Gender', 'Status',
    'Emergency contact (name)', 'Telephone', 'Date added to dashboard',
    'Updated at', 'Locale', 'Alternate phone 1', 'Alternate phone 2',
    'Contact person', 'Relationship', 'Relationship', 'Contact person',
    'Relationship', 'Relationship', 'Relationship', 'Relationship', 'Address',
    'Cell phone', 'Cell phone', 'Id [Nurse]', 'Email [Nurse]',
    'Reset password sent at [Nurse]', 'Remember created at [Nurse]',
    'Sign in count [Nurse]', 'Current sign in at [Nurse]',
    'Last sign in at [Nurse]', 'Current sign in ip [Nurse]',
    'Last sign in ip [Nurse]', 'Created at [Nurse]', 'Updated at [Nurse]',
    'Role [Nurse]', 'Phone [Nurse]', 'First name [Nurse]', 'Last name [Nurse]',
    'Locale [Nurse]', 'Timezone [Nurse]', 'Type [Nurse]',
    'Nurse supervisor [Nurse]', 'Family health unit name [Nurse]',
    'Confirmation token [Nurse]', 'Confirmed at [Nurse]',
    'Confirmation sent at [Nurse]', 'Unconfirmed email [Nurse]',
    'Id [Final appointment]', 'Appointment at [Final appointment]',
    'Appointment location [Final appointment]',
    'Phone returned [Final appointment]', 'Notes [Final appointment]',
    'Created at [Final appointment]', 'Updated at [Final appointment]',
    'Id [First appointment]', 'Appointment at [First appointment]',
    'Appointment location [First appointment]',
    'Session length [First appointment]', 'Notes [First appointment]',
    'Created at [First appointment]', 'Updated at [First appointment]',
    'Id [First contact]', 'Contact at [First contact]',
    'First appointment at [First contact]',
    'First appointment location [First contact]',
    'Created at [First contact]', 'Updated at [First contact]',
    'Id [Second contact]', 'Date/time of phone call [Second contact]',
    'Length of phone call (minutes) [Second contact]',
    'Notes [Second contact]', 'Created at [Second contact]',
    'Updated at [Second contact]',
    'Did the patient have any difficulties using CONEMO? [Second contact]',
    'Id [Smartphone]', 'Phone number / serial number [Smartphone]',
    'Created at [Smartphone]', 'Updated at [Smartphone]',
    'Phone ID [Smartphone]', 'Id [Third contact]',
    'Length of phone call (minutes) [Third contact]',
    'Created at [Third contact]', 'Updated at [Third contact]',
    'Notes [Third contact]', 'Date/time of phone call [Third contact]',
    'Q1 [Third contact]', 'Q2 [Third contact]', 'Q2 notes [Third contact]',
    'Q3 [Third contact]', 'Q3 notes [Third contact]', 'Q4 [Third contact]',
    'Q4 notes [Third contact]', 'Q5 [Third contact]',
    'Q5 notes [Third contact]',
    'Did the patient have any difficulties using CONEMO? [Third contact]',
    'Id [Content access events]', 'Accessed at [Content access events]',
    'Created at [Content access events]', 'Updated at [Content access events]',
    'Day in treatment accessed [Content access events]',
    'Lesson datum guid [Content access events]',
    'Dialogue datum guid [Content access events]',
    'Uuid [Content access events]',
    'Client created at [Content access events]',
    'Client updated at [Content access events]', 'Id [Devices]',
    'Uuid [Devices]', 'Device uuid [Devices]', 'Manufacturer [Devices]',
    'Model [Devices]', 'Platform [Devices]', 'Device version [Devices]',
    'Inserted at [Devices]', 'Created at [Devices]', 'Updated at [Devices]',
    'Last seen at [Devices]', 'Client created at [Devices]',
    'Client updated at [Devices]', 'Id [Help messages]',
    'Message [Help messages]', 'Read [Help messages]',
    'Staff message guid [Help messages]', 'Created at [Help messages]',
    'Updated at [Help messages]', 'Sent at [Help messages]',
    'Uuid [Help messages]', 'Client created at [Help messages]',
    'Client updated at [Help messages]', 'Id [Lessons]', 'Title [Lessons]',
    'Day in treatment [Lessons]', 'Locale [Lessons]', 'Created at [Lessons]',
    'Updated at [Lessons]', 'Guid [Lessons]',
    'Has activity planning [Lessons]', 'Pre planning content [Lessons]',
    'Post planning content [Lessons]', 'Non planning content [Lessons]',
    'Feedback after days [Lessons]', 'Planning response yes content [Lessons]',
    'Planning response no content [Lessons]',
    'Non planning response content [Lessons]', 'Activity choices [Lessons]',
    'Id [Logins]', 'Logged in at [Logins]', 'Created at [Logins]',
    'Updated at [Logins]', 'App login guid [Logins]', 'Uuid [Logins]',
    'App version [Logins]', 'Client created at [Logins]',
    'Client updated at [Logins]', 'Id [Nurse tasks]', 'Type [Nurse tasks]',
    'Status [Nurse tasks]', 'Scheduled at [Nurse tasks]',
    'Overdue at [Nurse tasks]', 'Created at [Nurse tasks]',
    'Updated at [Nurse tasks]', 'Id [Participant start dates]',
    'Date [Participant start dates]', 'Uuid [Participant start dates]',
    'Created at [Participant start dates]',
    'Updated at [Participant start dates]',
    'Client created at [Participant start dates]',
    'Client updated at [Participant start dates]', 'Id [Patient contacts]',
    'Contact reason [Patient contacts]', 'Note [Patient contacts]',
    'Contact at [Patient contacts]', 'Created at [Patient contacts]',
    'Updated at [Patient contacts]', 'Id [Planned activities]',
    'Uuid [Planned activities]', 'Name [Planned activities]',
    'Is complete [Planned activities]', 'Is help wanted [Planned activities]',
    'Level of happiness [Planned activities]',
    'How worthwhile [Planned activities]', 'Planned at [Planned activities]',
    'Lesson guid [Planned activities]', 'Created at [Planned activities]',
    'Updated at [Planned activities]',
    'Client created at [Planned activities]',
    'Client updated at [Planned activities]',
    'Follow up at [Planned activities]', 'Id [Session events]',
    'Event type [Session events]', 'Occurred at [Session events]',
    'Created at [Session events]', 'Updated at [Session events]',
    'Uuid [Session events]', 'Client created at [Session events]',
    'Client updated at [Session events]'
  ].freeze
end
